#! /bin/sh

set -e

CNFMOD="/usr/share/debconf/confmodule"
if [ -f "${CNFMOD}" ]; then
  . "${CNFMOD}"
fi

STABLEVERSION="20"
STABLEDIST="apricot"

compatcheck() {
  DISTRIB=$(lsb_release -is)
  RELEASE=$(lsb_release -rs)
  CODENAME=$(lsb_release -cs)
  KERNEL=$(uname -r)
  INCOMP=0
  SRCLIST="/etc/apt/sources.list"
  if [ "${DISTRIB}" != "Deepin" ]; then
    INCOMP=1
  elif [ "${CODENAME}" != "n/a" ]; then
    INCOMP=1
  else
    if dpkg --compare-versions "${RELEASE}" lt "${STABLEVERSION}"; then
      INCOMP=1
    else
      if [ -f "${SRCLIST}" ]; then
        DEBDIST=$(grep -E '^deb .*(/deepin/|/deepin-20-beta/)? ' "${SRCLIST}" \
          | sed -r 's/^.* (\S+) main .*$/\1/g')
        if [ -n "${DEBDIST}" ]; then
          if [ "${DEBDIST}" != "${STABLEDIST}" ]; then
            INCOMP=1
          fi
        fi
      fi
    fi
  fi
  if [ ${INCOMP} -ne 0 ]; then
    echo "================================================
Tienda Deepines solo es compatible con Deepin 20

 Recomendamos instalar una versión reciente de Deepin. Si está 
 usando Deepin 20, verifique que la configuración de los 
 repositorios no contenga errores.

 ---

Deepines Store is only compatible with Deepin 20

  We recommend installing a recent version of Deepin. If you are using
  Deepin 20, check that the configuration of the repositories 
  does not contain errors.
================================================"
    db_input critical deepines-repository/incompatible || true
    db_go || true
    exit 1
  fi
}

case "$1" in
  install|upgrade)
    compatcheck
    ;;
esac

exit 0
