name: CI
on:
  push:
    branches: nightly
    paths: '**.sh'
  pull_request:
    paths: '**.sh'
jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine
    steps:
      - name: Checkout Store repo
        id: checkout_repo
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Check scripts
        run: 'shellcheck --exclude SC2086,SC2317 ./*.sh'